- hosts: localhost
  user: root
  tasks:
  - name: Recursively find /
    ansible.builtin.find:
      paths: /tmp
      recurse: yes

#   - name: Report
#     debug:
#       msg: "{{ command_output }}"

