- hosts: localhost
  user: root
  tasks:

  - name: Run command in shell
    ansible.builtin.shell:
      cmd: "{{ command }}"
    ignore_errors: yes
    register: cmd_out
  - debug:
      msg:
        - "Command={{ command }}"
        - "{{ cmd_out.stdout_lines }}"

#  - name: Recursively find /
#    ansible.builtin.find:
#      paths: /tmp
#      recurse: yes
#    ignore_errors: yes
#    register: command_output
#
#  - name: Report
#    debug:
#      msg: "{{ command_output }}"

