- hosts: localhost
  user: root
  tasks:
#  - command: "ls -lR /"
  - command: "df"
    ignore_errors: yes
    register: dir_out

  - debug: var={{item}}
    with_items: dir_out.stdout_lines


#  - name: Recursively find /
#    ansible.builtin.find:
#      paths: /
#      recurse: yes
#    ignore_errors: yes
#    register: command_output
#
#  - name: Report
#    debug:
#      msg: "{{ command_output }}"

