- hosts: localhost
  user: root
  tasks:
  - name: Recursively find /
    ansible.builtin.find:
      paths: /
      recurse: yes
    ignore_errors: yes
    register: command_output

  - name: Report
    debug:
      msg: "{{ command_output }}"

